// Placeholder rookie data — realistic shape matching TIBER-Rookies producer output.
// NOT real 2026 prospects — fabricated names and numbers.
window.ROOKIES = [
  {
    slug: "wr-marcus-trenton",
    identity: {
      name: "Marcus Trenton",
      position: "WR",
      positionLabel: "Wide Receiver",
      school: "Ohio State",
      classYear: "Jr",
      height: "6'2\"",
      weight: "205 lbs",
      age: 20.8,
    },
    summary: {
      rookieGrade: 87.4,
      classRank: 3,
      posRank: 1,
      archetype: "Contested-Catch X",
      projection: "Year-1 WR3, Year-2 WR1 upside",
      profileSummary: "Big-slot frame with elite contested-catch and vertical-win translation. Age-adjusted production is 94th percentile among Power-5 WRs since 2018.",
    },
    evidenceTier: "strong_supported_edge",
    comps: { high: "DeAndre Hopkins", low: "Allen Robinson" },
    breakoutAge: 18.6,
    youngBreakoutFlag: true,
    breakoutLabel: "elite",
    breakoutAgeRating: 91,
    athleticSource: "SPORQ",
    scores: [
      { label: "Rookie Grade", value: 87.4 },
      { label: "Athletic (SPORQ)", value: 82 },
      { label: "Production", value: 94 },
      { label: "Draft Capital", value: 85 },
      { label: "Model Edge", value: 6.2 },
    ],
    pprProjection: { floor: 142, median: 214, ceiling: 286, band: "Starter" },
    metrics: [
      { label: "40 Yard Dash (s)", display: "4.42", value: 4.42, percent: 86, family: "speed" },
      { label: "Vertical (in)", display: "38.5", value: 38.5, percent: 82, family: "explosion" },
      { label: "Broad Jump (in)", display: "128", value: 128, percent: 78, family: "explosion" },
      { label: "3-Cone (s)", display: "6.82", value: 6.82, percent: 72, family: "agility" },
      { label: "Contested Catch Rate", display: "58.3%", value: 58.3, percent: 92, family: "production" },
      { label: "YAC / Reception", display: "6.4", value: 6.4, percent: 74, family: "production" },
    ],
    ageAdjustedProduction: 93.2,
    seasons: [
      { season: "2023", team: "Ohio State", statLine: { receptions: 52, receiving_yards: 847, receiving_tds: 9, yards_per_reception: 16.3, targets: 82 } },
      { season: "2024", team: "Ohio State", statLine: { receptions: 78, receiving_yards: 1342, receiving_tds: 14, yards_per_reception: 17.2, targets: 118 } },
      { season: "2025", team: "Ohio State", statLine: { receptions: 86, receiving_yards: 1498, receiving_tds: 16, yards_per_reception: 17.4, targets: 124 } },
    ],
    translationFlags: ["elite_contested_catch", "age_adjusted_target_share", "power5_volume_scaled", "vertical_win_rate"],
    contextFlags: ["alpha_target_share", "top_recruit"],
    evidenceSummary: "Multi-year ascending target share at a top-3 Power-5 program. Contested-catch rate and aDOT both grade in the 90th+ percentile among historical WR1 comps.",
    tags: ["Alpha X", "Day-1 starter", "Dynasty 1.01 candidate"],
  },
  {
    slug: "rb-devin-ashford",
    identity: {
      name: "Devin Ashford",
      position: "RB",
      positionLabel: "Running Back",
      school: "Georgia",
      classYear: "Jr",
      height: "5'11\"",
      weight: "218 lbs",
      age: 21.2,
    },
    summary: {
      rookieGrade: 82.1,
      classRank: 7,
      posRank: 1,
      archetype: "Three-down Lead",
      projection: "Committee lead rusher, plus pass-game",
      profileSummary: "Balanced three-down profile with route tree and pass-pro ready on day one. Explosion numbers grade out with historical Round-1 RBs.",
    },
    evidenceTier: "moderate_edge",
    comps: { high: "Josh Jacobs", low: "Rhamondre Stevenson" },
    breakoutAge: 19.4,
    youngBreakoutFlag: true,
    breakoutLabel: "strong",
    breakoutAgeRating: 78,
    athleticSource: "SPORQ",
    scores: [
      { label: "Rookie Grade", value: 82.1 },
      { label: "Athletic (SPORQ)", value: 76 },
      { label: "Production", value: 88 },
      { label: "Draft Capital", value: 80 },
      { label: "Model Edge", value: 2.8 },
    ],
    pprProjection: { floor: 118, median: 172, ceiling: 232, band: "Contributor" },
    metrics: [
      { label: "40 Yard Dash (s)", display: "4.48", value: 4.48, percent: 74, family: "speed" },
      { label: "Vertical (in)", display: "37.0", value: 37.0, percent: 78, family: "explosion" },
      { label: "Broad Jump (in)", display: "124", value: 124, percent: 72, family: "explosion" },
      { label: "Bench (reps)", display: "22", value: 22, percent: 82, family: "strength" },
      { label: "Yards After Contact", display: "3.8", value: 3.8, percent: 86, family: "production" },
      { label: "Receiving Yards/Game", display: "32.4", value: 32.4, percent: 81, family: "production" },
    ],
    ageAdjustedProduction: 84.1,
    seasons: [
      { season: "2023", team: "Georgia", statLine: { rush_attempts: 142, rush_yards: 714, rush_tds: 8, yards_per_carry: 5.0, receptions: 22, receiving_yards: 198 } },
      { season: "2024", team: "Georgia", statLine: { rush_attempts: 198, rush_yards: 1086, rush_tds: 12, yards_per_carry: 5.5, receptions: 34, receiving_yards: 284 } },
      { season: "2025", team: "Georgia", statLine: { rush_attempts: 214, rush_yards: 1284, rush_tds: 15, yards_per_carry: 6.0, receptions: 41, receiving_yards: 342 } },
    ],
    translationFlags: ["three_down_usage", "passing_down_snaps", "explosive_run_rate", "red_zone_efficiency"],
    contextFlags: ["sec_workload", "pass_protection_plus"],
    evidenceSummary: "High-volume SEC workload with sustained efficiency and pass-game usage. Pass-protection snaps grade in the top decile for the position class.",
    tags: ["Three-down", "Pass-game plus", "Early Round 1"],
  },
  {
    slug: "qb-cole-barrett",
    identity: {
      name: "Cole Barrett",
      position: "QB",
      positionLabel: "Quarterback",
      school: "Alabama",
      classYear: "Sr",
      height: "6'4\"",
      weight: "226 lbs",
      age: 22.4,
    },
    summary: {
      rookieGrade: 78.6,
      classRank: 12,
      posRank: 2,
      archetype: "Pocket Processor",
      projection: "Year-2 starter, Year-1 bridge/bench",
      profileSummary: "Structured, timing-based processor. Intermediate-area accuracy grades elite; deep-ball touch is a developmental flag.",
    },
    evidenceTier: "consensus_aligned",
    comps: { high: "Kirk Cousins", low: "Mac Jones" },
    breakoutAge: 20.2,
    youngBreakoutFlag: false,
    breakoutLabel: "average",
    breakoutAgeRating: 62,
    athleticSource: "COMBINE_FALLBACK",
    scores: [
      { label: "Rookie Grade", value: 78.6 },
      { label: "Athletic", value: 54 },
      { label: "Production", value: 82 },
      { label: "Draft Capital", value: 88 },
      { label: "Model Edge", value: -1.4 },
    ],
    pprProjection: { floor: 184, median: 248, ceiling: 312, band: "Contributor" },
    metrics: [
      { label: "40 Yard Dash (s)", display: "4.88", value: 4.88, percent: 32, family: "speed" },
      { label: "Vertical (in)", display: "29.0", value: 29.0, percent: 44, family: "explosion" },
      { label: "Completion %", display: "68.2%", value: 68.2, percent: 82, family: "production" },
      { label: "Adjusted Y/A", display: "8.4", value: 8.4, percent: 78, family: "production" },
      { label: "TD/INT Ratio", display: "4.2", value: 4.2, percent: 84, family: "production" },
      { label: "Pressure EPA/play", display: "-0.18", value: -0.18, percent: 71, family: "production" },
    ],
    ageAdjustedProduction: 74.8,
    seasons: [
      { season: "2023", team: "Alabama", statLine: { completions: 186, attempts: 284, completion_pct: 65.5, passing_yards: 2684, passing_tds: 22, interceptions: 7, yards_per_attempt: 9.5 } },
      { season: "2024", team: "Alabama", statLine: { completions: 248, attempts: 362, completion_pct: 68.5, passing_yards: 3412, passing_tds: 29, interceptions: 8, yards_per_attempt: 9.4 } },
      { season: "2025", team: "Alabama", statLine: { completions: 276, attempts: 404, completion_pct: 68.3, passing_yards: 3824, passing_tds: 34, interceptions: 8, yards_per_attempt: 9.5 } },
    ],
    translationFlags: ["timing_based_accuracy", "clean_pocket_efficiency", "red_zone_completion"],
    contextFlags: ["sec_competition", "clean_operational_reps"],
    evidenceSummary: "Three-year ascending starter in SEC offense with structured RPO + timing concepts. Grades cleanly in intermediate windows; deep shot is a tape concern.",
    tags: ["Pocket operator", "Draft capital lock", "Year-2 starter"],
  },
  {
    slug: "te-owen-hale",
    identity: {
      name: "Owen Hale",
      position: "TE",
      positionLabel: "Tight End",
      school: "Notre Dame",
      classYear: "Jr",
      height: "6'5\"",
      weight: "248 lbs",
      age: 21.0,
    },
    summary: {
      rookieGrade: 74.2,
      classRank: 18,
      posRank: 1,
      archetype: "Move-Y Receiver",
      projection: "Year-1 TE2, breakout Year-2",
      profileSummary: "Large-slot body with route nuance. Usage model already resembles NFL move-Y — red-zone target share is the standout signal.",
    },
    evidenceTier: "moderate_edge",
    comps: { high: "Dalton Kincaid", low: "Cole Kmet" },
    breakoutAge: 19.8,
    youngBreakoutFlag: true,
    breakoutLabel: "strong",
    breakoutAgeRating: 74,
    athleticSource: "SPORQ",
    scores: [
      { label: "Rookie Grade", value: 74.2 },
      { label: "Athletic (SPORQ)", value: 72 },
      { label: "Production", value: 78 },
      { label: "Draft Capital", value: 70 },
      { label: "Model Edge", value: 3.8 },
    ],
    pprProjection: { floor: 82, median: 128, ceiling: 184, band: "Contributor" },
    metrics: [
      { label: "40 Yard Dash (s)", display: "4.62", value: 4.62, percent: 72, family: "speed" },
      { label: "Vertical (in)", display: "36.0", value: 36.0, percent: 74, family: "explosion" },
      { label: "Broad Jump (in)", display: "122", value: 122, percent: 68, family: "explosion" },
      { label: "Red Zone Target Share", display: "28.4%", value: 28.4, percent: 88, family: "production" },
      { label: "YAC / Reception", display: "5.8", value: 5.8, percent: 76, family: "production" },
      { label: "Slot Rate", display: "64%", value: 64, percent: 82, family: "usage" },
    ],
    ageAdjustedProduction: 77.4,
    seasons: [
      { season: "2023", team: "Notre Dame", statLine: { receptions: 32, receiving_yards: 418, receiving_tds: 4, yards_per_reception: 13.1, targets: 48 } },
      { season: "2024", team: "Notre Dame", statLine: { receptions: 48, receiving_yards: 724, receiving_tds: 8, yards_per_reception: 15.1, targets: 68 } },
      { season: "2025", team: "Notre Dame", statLine: { receptions: 62, receiving_yards: 892, receiving_tds: 11, yards_per_reception: 14.4, targets: 84 } },
    ],
    translationFlags: ["move_y_alignment", "red_zone_dominance", "slot_usage_translation"],
    contextFlags: ["multi_align_usage"],
    evidenceSummary: "Multi-alignment usage profile with red-zone target share that historically translates to early TE1 seasons. Separation grade is average; body + catch radius carry the profile.",
    tags: ["Move-Y", "Red-zone mismatch", "TE1 upside"],
  },
  {
    slug: "wr-jalen-okafor",
    identity: {
      name: "Jalen Okafor",
      position: "WR",
      positionLabel: "Wide Receiver",
      school: "LSU",
      classYear: "So",
      height: "5'10\"",
      weight: "184 lbs",
      age: 19.9,
    },
    summary: {
      rookieGrade: 71.8,
      classRank: 24,
      posRank: 5,
      archetype: "Field-Stretching Z",
      projection: "Year-1 depth, high Year-2 variance",
      profileSummary: "True sophomore with an elite age-adjusted production curve. Frame is the gating concern — contested-catch sample is thin.",
    },
    evidenceTier: "watchlist_outlier",
    comps: { high: "Jaylen Waddle", low: "Marquez Valdes-Scantling" },
    breakoutAge: 18.2,
    youngBreakoutFlag: true,
    breakoutLabel: "elite",
    breakoutAgeRating: 88,
    athleticSource: "SPORQ",
    scores: [
      { label: "Rookie Grade", value: 71.8 },
      { label: "Athletic (SPORQ)", value: 89 },
      { label: "Production", value: 82 },
      { label: "Draft Capital", value: 55 },
      { label: "Model Edge", value: 5.4 },
    ],
    pprProjection: { floor: 62, median: 118, ceiling: 198, band: "Lottery" },
    metrics: [
      { label: "40 Yard Dash (s)", display: "4.31", value: 4.31, percent: 96, family: "speed" },
      { label: "Vertical (in)", display: "40.0", value: 40.0, percent: 92, family: "explosion" },
      { label: "Broad Jump (in)", display: "131", value: 131, percent: 88, family: "explosion" },
      { label: "3-Cone (s)", display: "6.68", value: 6.68, percent: 86, family: "agility" },
      { label: "Yards/Route Run", display: "3.1", value: 3.1, percent: 84, family: "production" },
      { label: "aDOT", display: "16.4", value: 16.4, percent: 82, family: "production" },
    ],
    ageAdjustedProduction: 88.6,
    seasons: [
      { season: "2024", team: "LSU", statLine: { receptions: 44, receiving_yards: 812, receiving_tds: 7, yards_per_reception: 18.5, targets: 74 } },
      { season: "2025", team: "LSU", statLine: { receptions: 68, receiving_yards: 1188, receiving_tds: 10, yards_per_reception: 17.5, targets: 102 } },
    ],
    translationFlags: ["age_adjusted_breakout", "speed_score_elite", "vertical_separation"],
    contextFlags: ["true_sophomore", "early_declare"],
    evidenceSummary: "True sophomore with an age-adjusted production curve in the top decile historically. Athletic composite is elite but frame is undersized relative to NFL X comps.",
    tags: ["Age outlier", "Speed score", "Contingent upside"],
  },
  {
    slug: "rb-isaiah-marks",
    identity: {
      name: "Isaiah Marks",
      position: "RB",
      positionLabel: "Running Back",
      school: "Texas",
      classYear: "Sr",
      height: "5'10\"",
      weight: "212 lbs",
      age: 22.6,
    },
    summary: {
      rookieGrade: 66.4,
      classRank: 38,
      posRank: 4,
      archetype: "Two-down Grinder",
      projection: "Backup/committee, thin pass-game",
      profileSummary: "Four-year producer with efficiency but limited third-down role. Age-at-entry + committee college profile both grade as yellow flags.",
    },
    evidenceTier: "consensus_aligned",
    comps: { high: "Zach Charbonnet", low: "Damien Harris" },
    breakoutAge: 20.8,
    youngBreakoutFlag: false,
    breakoutLabel: "average",
    breakoutAgeRating: 54,
    athleticSource: "COMBINE_FALLBACK",
    scores: [
      { label: "Rookie Grade", value: 66.4 },
      { label: "Athletic", value: 62 },
      { label: "Production", value: 74 },
      { label: "Draft Capital", value: 60 },
      { label: "Model Edge", value: -0.8 },
    ],
    pprProjection: { floor: 58, median: 96, ceiling: 148, band: "Lottery" },
    metrics: [
      { label: "40 Yard Dash (s)", display: "4.56", value: 4.56, percent: 58, family: "speed" },
      { label: "Vertical (in)", display: "34.0", value: 34.0, percent: 52, family: "explosion" },
      { label: "Broad Jump (in)", display: "118", value: 118, percent: 56, family: "explosion" },
      { label: "Bench (reps)", display: "18", value: 18, percent: 68, family: "strength" },
      { label: "Yards After Contact", display: "3.2", value: 3.2, percent: 62, family: "production" },
      { label: "Receiving Yards/Game", display: "14.2", value: 14.2, percent: 38, family: "production" },
    ],
    ageAdjustedProduction: 58.2,
    seasons: [
      { season: "2022", team: "Texas", statLine: { rush_attempts: 88, rush_yards: 398, rush_tds: 4, yards_per_carry: 4.5, receptions: 12, receiving_yards: 88 } },
      { season: "2023", team: "Texas", statLine: { rush_attempts: 142, rush_yards: 688, rush_tds: 7, yards_per_carry: 4.8, receptions: 14, receiving_yards: 112 } },
      { season: "2024", team: "Texas", statLine: { rush_attempts: 168, rush_yards: 842, rush_tds: 9, yards_per_carry: 5.0, receptions: 16, receiving_yards: 128 } },
      { season: "2025", team: "Texas", statLine: { rush_attempts: 186, rush_yards: 984, rush_tds: 11, yards_per_carry: 5.3, receptions: 18, receiving_yards: 142 } },
    ],
    translationFlags: ["between_tackles_efficiency", "red_zone_finishing"],
    contextFlags: ["age_at_entry_flag", "committee_usage"],
    evidenceSummary: "Consistent efficiency grader but limited pass-game sample and older draft entry. Profile translates to committee-lead outcomes historically.",
    tags: ["Committee", "Age flag", "Day-3 value"],
  },
];
